[build]
builder = "NIXPACKS"

[deploy]
startCommand = ". /opt/venv/bin/activate && uvicorn api.index:app --host 0.0.0.0 --port ${PORT:-3050}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
